services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: company_db
      POSTGRES_USER: company_user
      POSTGRES_PASSWORD: company_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=company_db
      - DB_USER=company_user
      - DB_PASSWORD=company_password

volumes:
  postgres_data: